// Copyright 2024 Google Inc. All Rights Reserved.
// Author: Hung-Te Lin <hungte@gmail.com>

// To create KeyboardEvent-like events.

import {jscin} from "../jscin/jscin.js";

// http://www.w3.org/TR/DOM-Level-3-Events/#events-KeyboardEvent
export const KeyToCode = {
  "Backspace":  "Backspace",
  "Tab":        "Tab",
  "\t":         "Tab",
  "Enter":      "Enter",
  "Shift":      "ShiftLeft",
  "Control":    "ControlLeft",
  "Alt":        "AltLeft",
  "Pause":      "Pause",
  "CapsLock":   "CapsLock",
  "Escape":     "Escape",
  " ":          "Space",
  "PageUp":     "PageUp",
  "PageDown":   "PageDown",
  "End":        "End",
  "Home":       "Home",
  "ArrowLeft":  "ArrowLeft",
  "ArrowUp":    "ArrowUp",
  "ArrowRight": "ArrowRight",
  "ArrowDown":  "ArrowDown",
  "Insert":     "Insert",
  "Delete":     "Delete",
  "0":          "Digit0",
  "1":          "Digit1",
  "2":          "Digit2",
  "3":          "Digit3",
  "4":          "Digit4",
  "5":          "Digit5",
  "6":          "Digit6",
  "7":          "Digit7",
  "8":          "Digit8",
  "9":          "Digit9",
  "a":          "KeyA",
  "b":          "KeyB",
  "c":          "KeyC",
  "d":          "KeyD",
  "e":          "KeyE",
  "f":          "KeyF",
  "g":          "KeyG",
  "h":          "KeyH",
  "i":          "KeyI",
  "j":          "KeyJ",
  "k":          "KeyK",
  "l":          "KeyL",
  "m":          "KeyM",
  "n":          "KeyN",
  "o":          "KeyO",
  "p":          "KeyP",
  "q":          "KeyQ",
  "r":          "KeyR",
  "s":          "KeyS",
  "t":          "KeyT",
  "u":          "KeyU",
  "v":          "KeyV",
  "w":          "KeyW",
  "x":          "KeyX",
  "y":          "KeyY",
  "z":          "KeyZ",
  "F1":         "F1",
  "F2":         "F2",
  "F3":         "F3",
  "F4":         "F4",
  "F5":         "F5",
  "F6":         "F6",
  "F7":         "F7",
  "F8":         "F8",
  "F9":         "F9",
  "F10":        "F10",
  "F11":        "F11",
  "F12":        "F12",
  "NumLock":    "NumLock",
  "ScrollLock": "ScrollLock",
  ";":          "Semicolon",
  "=":          "Equal",
  ",":          "Comma",
  "-":          "Minus",
  ".":          "Period",
  "/":          "Slash",
  "`":          "BackQuote",
  "[":          "BracketLeft",
  "/":          "Backslash",
  "]":          "BracketRight",
  "'":          "Quote",
};

export function CreateKeyEvent(key, code=undefined, type="keydown") {
  if (!code)
    code = (key in KeyToCode) ? KeyToCode[key] : key;

  return {
    type: type,

    key: key,
    code: code,

    ctrlKey: false,
    altKey: false,
    shiftKey: false,
    metaKey: false,
  };
}
